version: "3"
services:
  python:
    container_name: python
    build: python/.
    volumes: 
      - "./python:/usr/src/app"
    tty: true
  
  redis1:
    container_name: redis1
    build: redis/.
    restart: always
    ports:
      - "7001:6379"

  redis2:
    container_name: redis2
    build: redis/.
    restart: always
    ports:
      - "7002:6379"

  redis3:
    container_name: redis3
    build: redis/.
    restart: always
    ports:
      - "7003:6379"

  redis4:
    container_name: redis4
    build: redis/.
    restart: always
    ports:
      - "7004:6379"

  redis5:
    container_name: redis5
    build: redis/.
    restart: always
    ports:
      - "7005:6379"

  redis6:
    container_name: redis6
    build: redis/.
    restart: always
    ports:
      - "7006:6379"